
lychee.define('lychee.DIST').requires([
	'lychee.Input',
	'lychee.Renderer',
	'lychee.Stash',
	'lychee.Storage',
	'lychee.Viewport',
	'lychee.ai.Agent',
	'lychee.ai.Layer',
	'lychee.ai.bnn.Agent',
	'lychee.ai.bnn.Brain',
	'lychee.ai.bnn.Layer',
	'lychee.ai.enn.Agent',
	'lychee.ai.enn.Brain',
	'lychee.ai.enn.Genome',
	'lychee.ai.enn.Layer',
	'lychee.ai.neat.Agent',
	'lychee.ai.neat.Brain',
	'lychee.ai.neat.Gene',
	'lychee.ai.neat.Genome',
	'lychee.ai.neat.Pool',
	'lychee.ai.neat.Species',
	'lychee.app.Blueprint',
	'lychee.app.Element',
	'lychee.app.Entity',
	'lychee.app.Flow',
	'lychee.app.Jukebox',
	'lychee.app.Layer',
	'lychee.app.Loop',
	'lychee.app.Main',
	'lychee.app.Sprite',
	'lychee.app.State',
	'lychee.app.entity.Label',
	'lychee.app.entity.Text',
	'lychee.app.layer.Table',
	'lychee.app.sprite.Background',
	'lychee.app.sprite.Emblem',
	'lychee.codec.BENCODE',
	'lychee.codec.BITON',
	'lychee.codec.DIXY',
	'lychee.codec.INI',
	'lychee.codec.JSON',
	'lychee.crypto.BLAKE2B',
	'lychee.crypto.CRC32',
	'lychee.crypto.MD5',
	'lychee.crypto.MURMUR',
	'lychee.crypto.SHA1',
	'lychee.data.Tree',
	'lychee.data.tree.Oct',
	'lychee.data.tree.Quad',
	'lychee.effect.Alpha',
	'lychee.effect.Color',
	'lychee.effect.Depth',
	'lychee.effect.Event',
	'lychee.effect.Height',
	'lychee.effect.Music',
	'lychee.effect.Offset',
	'lychee.effect.Position',
	'lychee.effect.Radius',
	'lychee.effect.Shake',
	'lychee.effect.Sound',
	'lychee.effect.State',
	'lychee.effect.Velocity',
	'lychee.effect.Visible',
	'lychee.effect.Width',
	'lychee.event.Emitter',
	'lychee.event.Flow',
	'lychee.event.Queue',
	'lychee.event.Router',
	'lychee.math.Matrix',
	'lychee.math.Mersenne',
	'lychee.math.Quaternion',
	'lychee.math.Vector3',
	'lychee.math.Vector4',
	'lychee.net.Client',
	'lychee.net.Remote',
	'lychee.net.Server',
	'lychee.net.Service',
	'lychee.net.Tunnel',
	'lychee.net.protocol.HTTP',
	'lychee.net.protocol.WS',
	'lychee.net.service.Chat',
	'lychee.net.service.Debugger',
	'lychee.net.service.Session',
	'lychee.net.service.Stash',
	'lychee.net.service.Storage',
	'lychee.net.socket.HTTP',
	'lychee.net.socket.WS',
	'lychee.policy.Alpha',
	'lychee.policy.Color',
	'lychee.policy.Depth',
	'lychee.policy.Height',
	'lychee.policy.Music',
	'lychee.policy.Offset',
	'lychee.policy.Position',
	'lychee.policy.Radius',
	'lychee.policy.Shake',
	'lychee.policy.Sound',
	'lychee.policy.State',
	'lychee.policy.Velocity',
	'lychee.policy.Visible',
	'lychee.policy.Width',
	'lychee.ui.Blueprint',
	'lychee.ui.Element',
	'lychee.ui.Entity',
	'lychee.ui.Layer',
	'lychee.ui.Menu',
	'lychee.ui.Notice',
	'lychee.ui.Sprite',
	'lychee.ui.State',
	'lychee.ui.element.Input',
	'lychee.ui.element.Jukebox',
	'lychee.ui.element.Network',
	'lychee.ui.element.Search',
	'lychee.ui.element.Stash',
	'lychee.ui.element.Storage',
	'lychee.ui.element.Viewport',
	'lychee.ui.entity.Button',
	'lychee.ui.entity.Download',
	'lychee.ui.entity.Helper',
	'lychee.ui.entity.Input',
	'lychee.ui.entity.Joystick',
	'lychee.ui.entity.Label',
	'lychee.ui.entity.List',
	'lychee.ui.entity.Select',
	'lychee.ui.entity.Slider',
	'lychee.ui.entity.Switch',
	'lychee.ui.entity.Text',
	'lychee.ui.entity.Textarea',
	'lychee.ui.entity.Texture',
	'lychee.ui.entity.Upload',
	'lychee.ui.layer.Table',
	'lychee.ui.sprite.Background',
	'lychee.ui.sprite.Emblem',
	'lychee.verlet.Constraint',
	'lychee.verlet.Entity',
	'lychee.verlet.Layer'
]).exports((lychee, global, attachments) => {

	const Module = {

		// deserialize: function(blob) {},

		serialize: function() {

			return {
				'reference': 'lychee.DIST',
				'arguments': []
			};

		}

	};

	return Module;

});
